### ISSUE TITLE
PHP Warning: Expected array for frame X

### ISSUE THREAD

**Issue by bileslaw** [clue/reactphp-socks#103]
Hello,

It seems that some exceptions cannot be correctly converted to a string.

This is what sometime appears in my log (notice the empty stack traces):
```
[Sun, 06 Feb 2022 17:26:14 +0300] .ERROR: RuntimeException: Connection to 1.2.3.4:5678?hostname=qwerty.net timed out after 10 seconds (ETIMEDOUT) in /path-to-app/vendor/react/socket/src/TimeoutConnector.php:42
Stack trace:
#0 /path-to-app/vendor/react/promise/src/RejectedPromise.php(28): React\Socket\TimeoutConnector::React\Socket\{closure}()
#1 /path-to-app/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then()
#2 /path-to-app/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#3 /path-to-app/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#4 /path-to-app/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#5 /path-to-app/vendor/react/promise-timer/src/functions.php(183): React\Promise\Promise::React\Promise\{closure}()
#6 /path-to-app/vendor/react/event-loop/src/ExtUvLoop.php(120): React\Promise\Timer\{closure}()
#7 [internal function]: React\EventLoop\ExtUvLoop->React\EventLoop\{closure}()
#8 /path-to-app/vendor/react/event-loop/src/ExtUvLoop.php(232): uv_run()
#9 /path-to-app/vendor/react/event-loop/src/Loop.php(211): React\EventLoop\ExtUvLoop->run()
#10 /path-to-app/src/Main.php(22): React\EventLoop\Loop::run()
#11 /path-to-app/app(7): Main->__construct()
#12 {main}

Next RuntimeException: Connection to tcp://qwerty.net:443 failed because connection to proxy failed (ECONNREFUSED) in /path-to-app/vendor/clue/socks-react/src/Client.php:189
Stack trace:
#0 {main}

Next RuntimeException: Connection to tls://qwerty.net:443 failed because connection to proxy failed (ECONNREFUSED) in /path-to-app/vendor/react/socket/src/SecureConnector.php:75
Stack trace:
#0 {main}
```

And at the same time, in the PHP log:
```
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 0 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 1 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 2 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 3 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 4 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 5 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 6 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 7 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 8 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 9 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 10 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 11 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 12 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 13 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 14 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 15 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 16 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 17 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 18 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 19 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 20 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 21 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 22 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 23 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 0 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 1 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 2 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 3 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 4 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 5 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 6 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 7 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 8 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 9 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 10 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 11 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 12 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 13 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 14 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 15 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
[06-Feb-2022 17:26:14 Europe/Moscow] PHP Warning:  Expected array for frame 16 in /path-to-app/vendor/monolog/monolog/src/Monolog/Logger.php on line 565
```

**Comment by SimonFrings** [comment]
@bileslaw thanks for bringing this up. :+1: 

I'm having a hard time to reproduce this behavior, is there a script on your side that I can test this with?
I'm also not entirely sure but it seems like this is coming from the Monolog project and not from reactphp-socks.

What are your thoughts on this?

**Comment by bileslaw** [comment]
Hi @SimonFrings :wave:

I've just been able to find the minimal working example and the causing code.
The problem seems to come from the use of references in `foreach`.

```php
try {
	(function (): void {
		throw new Exception();
	})();
} catch (Exception $e) {}

// the following code is taken from
// <clue/socks-react/src/Client.php>
// <react/socket/src/SecureConnector.php>
// perhaps it's repeated in some other files

// avoid garbage references by replacing all closures in call stack.
// what a lovely piece of code!
$r = new \ReflectionProperty('Exception', 'trace');
$r->setAccessible(true);
$trace = $r->getValue($e);

// Exception trace arguments are not available on some PHP 7.4 installs
// @codeCoverageIgnoreStart
foreach ($trace as &$one) {
	if (isset($one['args'])) {
		foreach ($one['args'] as &$arg) {
			if ($arg instanceof \Closure) {
				$arg = 'Object(' . \get_class($arg) . ')';
			}
		}
	}
}
// @codeCoverageIgnoreEnd
$r->setValue($e, $trace);

// empty trace and the warning
echo (string) $e, "\n";
```

**Comment by clue** [comment]
@bileslaw Thank you for reporting, I can indeed reproduce the problem you're seeing with the gist you've provided!

This is indeed a nasty bug that has been introduced a while ago with https://github.com/clue/reactphp-socks/pull/82. This only happens on PHP 7+ when printing the exception trace (`$exception->getTraceAsString()`) which makes it kind of hard to test and is also why this hasn't caught our attention earlier.

I've started looking into this and will file a PR as soon as time allows :+1:

**Comment by bileslaw** [comment]
@clue Thank you for the prompt action!

Just in case, I note again: the same bug is also located in `react/socket` at least.

**Comment by clue** [comment]
@bileslaw Don't worry, on it already! See upstream PRs https://github.com/reactphp/socket/pull/284 ad https://github.com/reactphp/dns/pull/191.

I hope this helps! :+1: If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/clue) ❤️
